spring:
  application:
    name: jms
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trusted: com.message.queue.jms
    jms:
      listener:
        acknowledge-mode: auto
        concurrency: 1
  datasource:
    url: jdbc:mysql://localhost:3306/jms_demo
    username: root
    password: vaitheesh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jms:
  queue:
    name: message.queue